### PR TITLE
add sompy app and indexing vcfs

### PR DESCRIPTION
**Pull request by rebeccahaines1**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5)

### CODE REVIEW

**Review by aledj2 — COMMENTED** [review]
+@aledj2 

> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5#-:-N3Psq572lK5Dzj_Xt8W:bweg3f8)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @aledj2)

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @aledj2 and @rebeccahaines1)

___
*[`dxapp.json` line 2 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5#-N3Pswxh5tVomyyRHXLB:-N3Pswxh5tVomyyRHXLC:b-kncyxh) ([raw file](https://github.com/moka-guys/dnanexus_tso500_output_parser/blob/5ea5ee8da8135c5a7d3365c7a6c7ca15b96046c0/dxapp.json#L2)):*
> ```JSON
> {
> 	"name": "tso500_output_parser_v2.0",
> ```

can we use semantic versioning (v2.0.0). I think this may be v1.2.0
___
*[`src/code.sh` line 8 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5#-N3PtEuH-cw98WBeodPU:-N3PtEuH-cw98WBeodPV:b-ct8jt6) ([raw file](https://github.com/moka-guys/dnanexus_tso500_output_parser/blob/5ea5ee8da8135c5a7d3365c7a6c7ca15b96046c0/src/code.sh#L8)):*
> ```Shell
> # make output folder
> mkdir -p /home/dnanexus/out/logfiles/logfiles/ /home/dnanexus/out/vcf_index/vcf_index
> #install tabix (needed for indexing the vcfs)
> ```

remove if not used
___
*[`src/code.sh` line 119 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5#-N3PtpnQ39nnxVNUDVuL:-N3PtpnQ39nnxVNUDVuM:buyfwjd) ([raw file](https://github.com/moka-guys/dnanexus_tso500_output_parser/blob/5ea5ee8da8135c5a7d3365c7a6c7ca15b96046c0/src/code.sh#L119)):*
> ```Shell
>         cd /home/dnanexus/out/vcf_index/vcf_index
>         tabix -p vcf $filename.gz
>         cd ~
> ```

can we delete the downloaded vcf so we don't have duplicates in the project?

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @aledj2 and @rebeccahaines1)

___
*[`src/code.sh` line 118 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5#-N3TRbAF0CeasrX6cQoP:-N3TRbAGEPIwkV0WuMFv:b-zch9pr) ([raw file](https://github.com/moka-guys/dnanexus_tso500_output_parser/blob/5ea5ee8da8135c5a7d3365c7a6c7ca15b96046c0/src/code.sh#L118)):*
> ```Shell
>         bgzip -c $filename > $gzip_vcf_path
>         cd /home/dnanexus/out/vcf_index/vcf_index
>         tabix -p vcf $filename.gz
> ```

should this be tabix -p vcf $gzip_vcf_path

**Review by rebeccahaines1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @aledj2)

___
*[`dxapp.json` line 2 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5#-N3Pswxh5tVomyyRHXLB:-N3TmeS14T7L8Xk0XFvl:bb7f2mf) ([raw file](https://github.com/moka-guys/dnanexus_tso500_output_parser/blob/5ea5ee8da8135c5a7d3365c7a6c7ca15b96046c0/dxapp.json#L2)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can we use semantic versioning (v2.0.0). I think this may be v1.2.0
</blockquote></details>

done
___
*[`src/code.sh` line 8 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5#-N3PtEuH-cw98WBeodPU:-N3TmgFd-ysno0mERddn:bb7f2mf) ([raw file](https://github.com/moka-guys/dnanexus_tso500_output_parser/blob/5ea5ee8da8135c5a7d3365c7a6c7ca15b96046c0/src/code.sh#L8)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

remove if not used
</blockquote></details>

done
___
*[`src/code.sh` line 118 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5#-N3TRbAF0CeasrX6cQoP:-N3TmiqQ802IMcBQGdl1:b-x1s9as) ([raw file](https://github.com/moka-guys/dnanexus_tso500_output_parser/blob/5ea5ee8da8135c5a7d3365c7a6c7ca15b96046c0/src/code.sh#L118)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

should this be tabix -p vcf $gzip_vcf_path
</blockquote></details>

probably, it's doing the same thing.
Have changed this section to output the indexed vcfs to the results folder
___
*[`src/code.sh` line 119 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5#-N3PtpnQ39nnxVNUDVuL:-N3TmopZ5IkF2qay2_Wv:bsk6fvg) ([raw file](https://github.com/moka-guys/dnanexus_tso500_output_parser/blob/5ea5ee8da8135c5a7d3365c7a6c7ca15b96046c0/src/code.sh#L119)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can we delete the downloaded vcf so we don't have duplicates in the project?
</blockquote></details>

the downloaded vcf isn't output, only the bgzipped vcf. This could be deleted but it makes loading it in IGV very slow

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @aledj2 and @rebeccahaines1)

___
*[`src/code.sh` line 118 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5#-N3TRbAF0CeasrX6cQoP:-N3U-Dzz19_4ylYJOANM:b-3e7pi7) ([raw file](https://github.com/moka-guys/dnanexus_tso500_output_parser/blob/5ea5ee8da8135c5a7d3365c7a6c7ca15b96046c0/src/code.sh#L118)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

probably, it's doing the same thing.
Have changed this section to output the indexed vcfs to the results folder
</blockquote></details>

I'm a little confused as to what filefolder is returning (line 115)
___
*[`src/code.sh` line 119 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5#-N3PtpnQ39nnxVNUDVuL:-N3U-_Tx-p348FAzXGMv:bj5v4r6) ([raw file](https://github.com/moka-guys/dnanexus_tso500_output_parser/blob/5ea5ee8da8135c5a7d3365c7a6c7ca15b96046c0/src/code.sh#L119)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

the downloaded vcf isn't output, only the bgzipped vcf. This could be deleted but it makes loading it in IGV very slow
</blockquote></details>

OK, missed the bgzip step!
___
*[`src/code.sh` line 117 at r3](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5#-N3Txve46b158SKI3pC_:-N3Txve56Lp2Vd0SUMfI:bd91rkq) ([raw file](https://github.com/moka-guys/dnanexus_tso500_output_parser/blob/129cddfea8b6a72d647572cae1b117ae7b134658/src/code.sh#L117)):*
> ```Shell
>         filefolder=$(jq -r '.folder' <<< $genome_vcf)
>         #gzip_vcf_path=/home/dnanexus/out/vcf_index/vcf_index/$filename.gz
>         gzip_vcf_path=$vcf_index_output$filefolder
> ```

is there a missing / between the two variables?
___
*[`src/code.sh` line 121 at r3](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5#-N3TyVzm4YoSwFloSVrU:-N3TyVzm4YoSwFloSVrV:b-42u0oa) ([raw file](https://github.com/moka-guys/dnanexus_tso500_output_parser/blob/129cddfea8b6a72d647572cae1b117ae7b134658/src/code.sh#L121)):*
> ```Shell
>         gzip_vcf=$gzip_vcf_path/$filename.gz
>         bgzip -c $filename > $gzip_vcf
>         cd $gzip_vcf_path
> ```

so creating a folder for each sample/vcf, creating the filepath, bgzipping with the filepath (into a subflder) then cd-ing into subfolder and then indexing into the subfolder? not the easiest to follow! 

could you comment or

mkdir -p $gzip_vcf_path && cd "$_"
bgzip -c ../$filename > filename.gz 
tabix -p vcf $filename.gz
cd ..



_Code quote:_
```Shell

        gzip_vcf=$gzip_vcf_path/$filename.gz
        bgzip -c $filename > $gzip_vcf
        cd $gzip_vcf_path
        tabix -p vcf $gzip_vcf
```

**Review by rebeccahaines1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @aledj2)

___
*[`src/code.sh` line 118 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5#-N3TRbAF0CeasrX6cQoP:-N3U7Zte6XgEnV8MNCKp:b-jbct54) ([raw file](https://github.com/moka-guys/dnanexus_tso500_output_parser/blob/5ea5ee8da8135c5a7d3365c7a6c7ca15b96046c0/src/code.sh#L118)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

I'm a little confused as to what filefolder is returning (line 115)
</blockquote></details>

It's taking the path (folder) of the vcf file from the json generated by dx describe, which is used to make sure the zipped vcf and index ends up in the write folder afterwards.
___
*[`src/code.sh` line 117 at r3](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5#-N3Txve46b158SKI3pC_:-N3U443eAvA81bMP3RaP:b-avprvd) ([raw file](https://github.com/moka-guys/dnanexus_tso500_output_parser/blob/129cddfea8b6a72d647572cae1b117ae7b134658/src/code.sh#L117)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

is there a missing / between the two variables?
</blockquote></details>

no- $vcf_index_output ends with a "/"
I do need to delete the commented out line above it though
___
*[`src/code.sh` line 121 at r3](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5#-N3TyVzm4YoSwFloSVrU:-N3U7OFD5xLMtJGJQLVE:ba99g4b) ([raw file](https://github.com/moka-guys/dnanexus_tso500_output_parser/blob/129cddfea8b6a72d647572cae1b117ae7b134658/src/code.sh#L121)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

so creating a folder for each sample/vcf, creating the filepath, bgzipping with the filepath (into a subflder) then cd-ing into subfolder and then indexing into the subfolder? not the easiest to follow! 

could you comment or

mkdir -p $gzip_vcf_path && cd "$_"
bgzip -c ../$filename > filename.gz 
tabix -p vcf $filename.gz
cd ..
</blockquote></details>

Have added comments to clarify. This step is creating the paths and adding the bgzipped vcf and index to the sample folder in analysis_folder/Results

**Review by aledj2 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @aledj2)

___
*[`src/code.sh` line 117 at r3](https://reviewable.io/reviews/moka-guys/dnanexus_tso500_output_parser/5#-N3Txve46b158SKI3pC_:-N3UkpyIDfO7K7gMtBAr:bn1q81j) ([raw file](https://github.com/moka-guys/dnanexus_tso500_output_parser/blob/129cddfea8b6a72d647572cae1b117ae7b134658/src/code.sh#L117)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

no- $vcf_index_output ends with a "/"
I do need to delete the commented out line above it though
</blockquote></details>

on line 8?

**Pull request merged**
